- name: Install required packages for hardware related scripts
  ansible.builtin.package:
    name:
      - hddtemp
    state: present

- name: Copy hw related scripts
  ansible.builtin.copy:
    src: "motd/{{ item }}.sh"
    dest: /etc/update-motd.d/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items: '{{ motd_hw_scripts }}'
