# Enabling passwordless sudo must be first as the next step removes admin user's password
# and when the playbook is run for the first time with password, it fails
- name: "Enable passwordless sudo for admin user"
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ users_admin_username }}"
    line: "{{ users_admin_username }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

- name: "Create admin user"
  ansible.builtin.user:
    name: "{{ users_admin_username }}"
    shell: /bin/bash
    password: '*' # Disables user's password
    groups:
      - sudo
    state: present

- name: Set admin user SSH keys
  ansible.posix.authorized_key:
    user: "{{ users_admin_username }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ users_admin_public_keys }}"

- name: "Tighten admin user's home directory permissions"
  ansible.builtin.file:
    path: "/home/{{ users_admin_username }}"
    state: directory
    owner: "{{ users_admin_username }}"
    group: "{{ users_admin_username }}"
    mode: 0750
