# users_admin_password
# users_admin_password_salt
# users_admin_name
# users_admin_keys
# users_root_password
# users_root_password_salt

users_admin_passwordless_sudo: true
users_admin_groups:
  - sudo
